apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: ekses.crp.allianz.com
spec:
  group: crp.allianz.com
  names:  
    kind: XEks
    plural: xekses
  claimNames:
    kind: Eks
    plural: ekses
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    type: string
                required:
                  - name
            
            required:
              - parameters
